name: mongo-sharding-repl

services:
  # Конфигурационные серверы
  configsvr1:
    container_name: configsvr1
    image: mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27017
    volumes:
      - configsvr1_data:/data/db
    ports:
      - "27017:27017"

  # Шард 1 с репликацией
  shard1_primary:
    container_name: shard1_primary
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1 --port 27017
    volumes:
      - shard1_primary_data:/data/db
    ports:
      - "27018:27017"

  shard1_secondary1:
    container_name: shard1_secondary1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1 --port 27017
    volumes:
      - shard1_secondary1_data:/data/db
    ports:
      - "27019:27017"

  shard1_secondary2:
    container_name: shard1_secondary2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1 --port 27017
    volumes:
      - shard1_secondary2_data:/data/db
    ports:
      - "27020:27017"

  # Шард 2 с репликацией
  shard2_primary:
    container_name: shard2_primary
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2 --port 27017
    volumes:
      - shard2_primary_data:/data/db
    ports:
      - "27021:27017"

  shard2_secondary1:
    container_name: shard2_secondary1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2 --port 27017
    volumes:
      - shard2_secondary1_data:/data/db
    ports:
      - "27022:27017"

  shard2_secondary2:
    container_name: shard2_secondary2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2 --port 27017
    volumes:
      - shard2_secondary2_data:/data/db
    ports:
      - "27023:27017"

  # Маршрутизатор (mongos)
  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb configReplSet/configsvr1:27017 --port 27017
    ports:
      - "27024:27017"
    depends_on:
      - configsvr1
      - shard1_primary
      - shard2_primary

volumes:
  configsvr1_data:
  shard1_primary_data:
  shard1_secondary1_data:
  shard1_secondary2_data:
  shard2_primary_data:
  shard2_secondary1_data:
  shard2_secondary2_data: